# Generated by Django 4.0.6 on 2022-11-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_buynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Credit Card', 'Credit Card'), ('Paypal', 'Paypal')], default='pending', max_length=50),
        ),
    ]
