# Generated by Django 4.0.6 on 2022-11-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_orderplaced_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
